name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: go to directory
      run: cd indexcylla-cpp
    - name: make
      run: make
    - name: make clean
      run: make clean
